/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import backend.datatypes.Candidate;
import backend.datatypes.Voter;
import backend.managerClasses.SystemManager;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.DefaultMetalTheme;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.metal.OceanTheme;

/**
 *
 * @author Cliftonb
 */
public class MainMenu extends javax.swing.JFrame {

	// Specify the look and feel to use by defining the LOOKANDFEEL constant
	// Valid values are: null (use the default), "Metal", "System", "Motif",
	// and "GTK"
	final static String LOOKANDFEEL = "Motif";

	// If you choose the Metal L&F, you can also choose a theme.
	// Specify the theme to use by defining the THEME constant
	// Valid values are: "DefaultMetal", "Ocean",  and "Test"
	final static String THEME = "DefaultMetal";

	private SystemManager systemManager;

	/**
	 * Creates new form MainMenu
	 */
	public MainMenu() {
		initLookAndFeel();
		initComponents();

		systemManager = new SystemManager();
		updateVoteForCandidatesPanel(systemManager.cm.getCurrentCandidate());
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel17 = new javax.swing.JLabel();
                jButton12 = new javax.swing.JButton();
                tabbedPaneMenu = new javax.swing.JTabbedPane();
                viewCandidatePanel = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                showCandidatesTextArea = new javax.swing.JTextArea();
                showCandidatesButton = new javax.swing.JButton();
                viewCandidatesErrorLabel = new javax.swing.JLabel();
                viewVotersPanel = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                showVotersTextArea = new javax.swing.JTextArea();
                showVotersButton = new javax.swing.JButton();
                viewVotersErrorLabel = new javax.swing.JLabel();
                addCandidatePanel = new javax.swing.JPanel();
                candidateIDField = new javax.swing.JTextField();
                candidateFirstNameField = new javax.swing.JTextField();
                candidateSurnameField = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                candidateGradeComboBox = new javax.swing.JComboBox<>();
                candidateClassComboBox = new javax.swing.JComboBox<>();
                candidateAddButton = new javax.swing.JButton();
                candidatesErrorLabel = new javax.swing.JLabel();
                addVoterPanel = new javax.swing.JPanel();
                voterIDTextField = new javax.swing.JTextField();
                voterUsernameTextField = new javax.swing.JTextField();
                voterPasswordTextField = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                voterGradeComboBox = new javax.swing.JComboBox<>();
                voterClassComboBox = new javax.swing.JComboBox<>();
                addVoterButton = new javax.swing.JButton();
                jLabel9 = new javax.swing.JLabel();
                voterConfirmPasswordTextField = new javax.swing.JTextField();
                voterFirstNameTextField = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                voterSurnameTextField = new javax.swing.JTextField();
                voterErrorLabel = new javax.swing.JLabel();
                voteForCandidatePanel = new javax.swing.JPanel();
                votingCandidateFirstName = new javax.swing.JTextField();
                votingCandidateSurname = new javax.swing.JTextField();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                voteForCandidateButton = new javax.swing.JButton();
                voteForCandidateStartButton = new javax.swing.JButton();
                voteForCandidateNextButton = new javax.swing.JButton();
                voteForCandidatePreviousButton = new javax.swing.JButton();
                voteForCandidateEndButton = new javax.swing.JButton();
                voteForCandidateImageLabel = new javax.swing.JLabel();
                voteForCandidateErrorLabel = new javax.swing.JLabel();
                calculateVotesPanel = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                calculateVotesTextArea = new javax.swing.JTextArea();
                calculateVotesButton = new javax.swing.JButton();
                calculateVotesErrorLabel = new javax.swing.JLabel();
                setDatesPanel = new javax.swing.JPanel();
                startDateTextField = new javax.swing.JTextField();
                endDateTextField = new javax.swing.JTextField();
                setDatesButton = new javax.swing.JButton();
                jLabel15 = new javax.swing.JLabel();
                jLabel16 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                setDatesErrorLabel = new javax.swing.JLabel();
                jPanel8 = new javax.swing.JPanel();
                viewCandidateHelpButton = new javax.swing.JButton();
                viewVotersHelpButton = new javax.swing.JButton();
                addCandidateHelpButton = new javax.swing.JButton();
                addVoterHelpButton = new javax.swing.JButton();
                voteForCandidateHelpButton = new javax.swing.JButton();
                calculateVotesHelpButton = new javax.swing.JButton();
                setDatesHelpButton = new javax.swing.JButton();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jLabel19 = new javax.swing.JLabel();
                helpErrorLabel = new javax.swing.JLabel();

                jLabel17.setText("jLabel17");

                jButton12.setText("jButton12");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                tabbedPaneMenu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
                tabbedPaneMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
                tabbedPaneMenu.setOpaque(true);
                tabbedPaneMenu.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                tabbedPaneMenuStateChanged(evt);
                        }
                });

                showCandidatesTextArea.setEditable(false);
                showCandidatesTextArea.setColumns(20);
                showCandidatesTextArea.setRows(5);
                jScrollPane1.setViewportView(showCandidatesTextArea);

                showCandidatesButton.setText("Show All Candidates");
                showCandidatesButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                showCandidatesButtonActionPerformed(evt);
                        }
                });

                viewCandidatesErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

                javax.swing.GroupLayout viewCandidatePanelLayout = new javax.swing.GroupLayout(viewCandidatePanel);
                viewCandidatePanel.setLayout(viewCandidatePanelLayout);
                viewCandidatePanelLayout.setHorizontalGroup(
                        viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(viewCandidatePanelLayout.createSequentialGroup()
                                .addGroup(viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(viewCandidatePanelLayout.createSequentialGroup()
                                                .addGap(201, 201, 201)
                                                .addComponent(showCandidatesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(viewCandidatePanelLayout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addGroup(viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(viewCandidatesErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(50, Short.MAX_VALUE))
                );
                viewCandidatePanelLayout.setVerticalGroup(
                        viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(viewCandidatePanelLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(showCandidatesButton)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewCandidatesErrorLabel)
                                .addContainerGap())
                );

                tabbedPaneMenu.addTab("View Candidates", viewCandidatePanel);

                showVotersTextArea.setEditable(false);
                showVotersTextArea.setColumns(20);
                showVotersTextArea.setRows(5);
                jScrollPane2.setViewportView(showVotersTextArea);

                showVotersButton.setText("Show All Voters");
                showVotersButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                showVotersButtonActionPerformed(evt);
                        }
                });

                viewVotersErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

                javax.swing.GroupLayout viewVotersPanelLayout = new javax.swing.GroupLayout(viewVotersPanel);
                viewVotersPanel.setLayout(viewVotersPanelLayout);
                viewVotersPanelLayout.setHorizontalGroup(
                        viewVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(viewVotersPanelLayout.createSequentialGroup()
                                .addGroup(viewVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(viewVotersPanelLayout.createSequentialGroup()
                                                .addGap(201, 201, 201)
                                                .addComponent(showVotersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(viewVotersPanelLayout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addGroup(viewVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                                        .addComponent(viewVotersErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(50, Short.MAX_VALUE))
                );
                viewVotersPanelLayout.setVerticalGroup(
                        viewVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(viewVotersPanelLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(showVotersButton)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewVotersErrorLabel)
                                .addContainerGap())
                );

                tabbedPaneMenu.addTab("View Voters", viewVotersPanel);

                jLabel1.setText("Candidate Class");

                jLabel2.setText("Candidate ID");

                jLabel3.setText("Candidate First Name");

                jLabel4.setText("Candidate Surname");

                candidateGradeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12" }));

                candidateClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R", "E" }));

                candidateAddButton.setText("Add Candidate");
                candidateAddButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                candidateAddButtonActionPerformed(evt);
                        }
                });

                candidatesErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

                javax.swing.GroupLayout addCandidatePanelLayout = new javax.swing.GroupLayout(addCandidatePanel);
                addCandidatePanel.setLayout(addCandidatePanelLayout);
                addCandidatePanelLayout.setHorizontalGroup(
                        addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCandidatePanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(candidatesErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(addCandidatePanelLayout.createSequentialGroup()
                                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(candidateSurnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                                                .addGroup(addCandidatePanelLayout.createSequentialGroup()
                                                                        .addComponent(candidateGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(candidateClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(candidateFirstNameField)
                                                                .addComponent(candidateIDField))
                                                        .addComponent(candidateAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(47, 47, 47))
                );
                addCandidatePanelLayout.setVerticalGroup(
                        addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addCandidatePanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(candidateIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(candidateFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(candidateSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(candidateGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(candidateClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                .addComponent(candidateAddButton)
                                .addGap(56, 56, 56)
                                .addComponent(candidatesErrorLabel)
                                .addGap(32, 32, 32))
                );

                tabbedPaneMenu.addTab("Add Candidate", addCandidatePanel);

                jLabel5.setText("Voter Class");

                jLabel6.setText("Voter ID");

                jLabel7.setText("Voter Username");

                jLabel8.setText("Voter Password");

                voterGradeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12" }));

                voterClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R", "E" }));

                addVoterButton.setText("Add Voter");
                addVoterButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addVoterButtonActionPerformed(evt);
                        }
                });

                jLabel9.setText("Confirm Password");

                jLabel10.setText("Voter First Name");

                jLabel11.setText("Voter Surname");

                voterErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

                javax.swing.GroupLayout addVoterPanelLayout = new javax.swing.GroupLayout(addVoterPanel);
                addVoterPanel.setLayout(addVoterPanelLayout);
                addVoterPanelLayout.setHorizontalGroup(
                        addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVoterPanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(voterErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(addVoterPanelLayout.createSequentialGroup()
                                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(addVoterPanelLayout.createSequentialGroup()
                                                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(addVoterPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                                .addGap(61, 61, 61))
                                                        .addGroup(addVoterPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(28, 28, 28)))
                                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(voterPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                                        .addComponent(voterUsernameTextField)
                                                        .addComponent(voterIDTextField)
                                                        .addComponent(addVoterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(voterConfirmPasswordTextField)
                                                        .addComponent(voterFirstNameTextField)))
                                        .addGroup(addVoterPanelLayout.createSequentialGroup()
                                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(addVoterPanelLayout.createSequentialGroup()
                                                                .addComponent(voterGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(voterClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(voterSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(47, 47, 47))
                );
                addVoterPanelLayout.setVerticalGroup(
                        addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addVoterPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(voterIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(voterUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(voterPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(voterConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(voterFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(voterSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(voterGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(voterClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(addVoterButton)
                                .addGap(63, 63, 63)
                                .addComponent(voterErrorLabel)
                                .addGap(25, 25, 25))
                );

                tabbedPaneMenu.addTab("Add Voter", addVoterPanel);

                votingCandidateFirstName.setEditable(false);

                votingCandidateSurname.setEditable(false);

                jLabel13.setText("Candidate First Name");

                jLabel14.setText("Candidate Surname");

                voteForCandidateButton.setText("Vote");
                voteForCandidateButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                voteForCandidateButtonActionPerformed(evt);
                        }
                });

                voteForCandidateStartButton.setText("<<");
                voteForCandidateStartButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                voteForCandidateStartButtonActionPerformed(evt);
                        }
                });

                voteForCandidateNextButton.setText(">");
                voteForCandidateNextButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                voteForCandidateNextButtonActionPerformed(evt);
                        }
                });

                voteForCandidatePreviousButton.setText("<");
                voteForCandidatePreviousButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                voteForCandidatePreviousButtonActionPerformed(evt);
                        }
                });

                voteForCandidateEndButton.setText(">>");
                voteForCandidateEndButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                voteForCandidateEndButtonActionPerformed(evt);
                        }
                });

                voteForCandidateErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

                javax.swing.GroupLayout voteForCandidatePanelLayout = new javax.swing.GroupLayout(voteForCandidatePanel);
                voteForCandidatePanel.setLayout(voteForCandidatePanelLayout);
                voteForCandidatePanelLayout.setHorizontalGroup(
                        voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, voteForCandidatePanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(voteForCandidateErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(voteForCandidatePanelLayout.createSequentialGroup()
                                                .addGroup(voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(votingCandidateSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                                        .addComponent(votingCandidateFirstName)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, voteForCandidatePanelLayout.createSequentialGroup()
                                                                .addGroup(voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(voteForCandidatePanelLayout.createSequentialGroup()
                                                                                .addComponent(voteForCandidateStartButton)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(voteForCandidatePreviousButton)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(voteForCandidateNextButton))
                                                                        .addGroup(voteForCandidatePanelLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addGroup(voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(voteForCandidateImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(voteForCandidateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(voteForCandidateEndButton)
                                                                .addGap(5, 5, 5)))))
                                .addGap(47, 47, 47))
                );
                voteForCandidatePanelLayout.setVerticalGroup(
                        voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(voteForCandidatePanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(votingCandidateFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(votingCandidateSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(voteForCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(voteForCandidateStartButton)
                                        .addComponent(voteForCandidateNextButton)
                                        .addComponent(voteForCandidateEndButton)
                                        .addComponent(voteForCandidatePreviousButton))
                                .addGap(30, 30, 30)
                                .addComponent(voteForCandidateImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(voteForCandidateButton)
                                .addGap(41, 41, 41)
                                .addComponent(voteForCandidateErrorLabel)
                                .addGap(31, 31, 31))
                );

                tabbedPaneMenu.addTab("Vote For Candidate", voteForCandidatePanel);

                calculateVotesTextArea.setEditable(false);
                calculateVotesTextArea.setColumns(20);
                calculateVotesTextArea.setRows(5);
                jScrollPane3.setViewportView(calculateVotesTextArea);

                calculateVotesButton.setText("Show Votes");
                calculateVotesButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                calculateVotesButtonActionPerformed(evt);
                        }
                });

                calculateVotesErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

                javax.swing.GroupLayout calculateVotesPanelLayout = new javax.swing.GroupLayout(calculateVotesPanel);
                calculateVotesPanel.setLayout(calculateVotesPanelLayout);
                calculateVotesPanelLayout.setHorizontalGroup(
                        calculateVotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calculateVotesPanelLayout.createSequentialGroup()
                                .addGroup(calculateVotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(calculateVotesPanelLayout.createSequentialGroup()
                                                .addGap(201, 201, 201)
                                                .addComponent(calculateVotesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(calculateVotesPanelLayout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addGroup(calculateVotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                                        .addComponent(calculateVotesErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(50, Short.MAX_VALUE))
                );
                calculateVotesPanelLayout.setVerticalGroup(
                        calculateVotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calculateVotesPanelLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(calculateVotesButton)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculateVotesErrorLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                tabbedPaneMenu.addTab("Calculate Votes", calculateVotesPanel);

                endDateTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

                setDatesButton.setText("Set Dates");

                jLabel15.setText("Start Date");

                jLabel16.setText("End Date");

                jLabel18.setText("Formate: YYYY/MM/DD");

                setDatesErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

                javax.swing.GroupLayout setDatesPanelLayout = new javax.swing.GroupLayout(setDatesPanel);
                setDatesPanel.setLayout(setDatesPanelLayout);
                setDatesPanelLayout.setHorizontalGroup(
                        setDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(setDatesPanelLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(setDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(setDatesErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(setDatesPanelLayout.createSequentialGroup()
                                                .addGroup(setDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(setDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(setDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(endDateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                                                .addComponent(startDateTextField))
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(setDatesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(50, Short.MAX_VALUE))
                );
                setDatesPanelLayout.setVerticalGroup(
                        setDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(setDatesPanelLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(setDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(setDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(37, 37, 37)
                                .addComponent(setDatesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                .addComponent(setDatesErrorLabel)
                                .addGap(41, 41, 41))
                );

                tabbedPaneMenu.addTab("Set Dates", setDatesPanel);

                viewCandidateHelpButton.setText("View Candidates");

                viewVotersHelpButton.setText("View Voters");

                addCandidateHelpButton.setText("Add Candidate");

                addVoterHelpButton.setText("Add Voter");

                voteForCandidateHelpButton.setText("Vote For Candidate");

                calculateVotesHelpButton.setText("Calculate Votes");

                setDatesHelpButton.setText("Set Dates");

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane4.setViewportView(jTextArea1);

                jLabel19.setText("Click on the button below to find help on a particular topic:");

                helpErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(voteForCandidateHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(addVoterHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(addCandidateHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(viewVotersHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(viewCandidateHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addComponent(calculateVotesHelpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(setDatesHelpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(34, 34, 34)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(helpErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(60, Short.MAX_VALUE))
                );
                jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel19)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane4)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(viewCandidateHelpButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(viewVotersHelpButton)
                                                .addGap(28, 28, 28)
                                                .addComponent(addCandidateHelpButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(addVoterHelpButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(voteForCandidateHelpButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(calculateVotesHelpButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(setDatesHelpButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(helpErrorLabel)
                                .addGap(38, 38, 38))
                );

                tabbedPaneMenu.addTab("Help", jPanel8);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabbedPaneMenu)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabbedPaneMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void candidateAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateAddButtonActionPerformed
		if (systemManager.admin != null) {
			String CID = candidateIDField.getText();
			String CFirstName = candidateFirstNameField.getText();
			String CSurname = candidateSurnameField.getText();
			String CClass = candidateGradeComboBox.getSelectedItem() + "" + candidateClassComboBox.getSelectedItem();

			try {
				systemManager.cm.addNewCandidate(new Candidate(CID, CFirstName, CSurname, null, 0, CClass));
				candidatesErrorLabel.setText("Added successfully");
			} catch (SQLException ex) {
				candidatesErrorLabel.setText("Could not access database");
				System.out.println("UI: Could not access database");
				Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			candidatesErrorLabel.setText("You do not have permission to add candidates");
		}

        }//GEN-LAST:event_candidateAddButtonActionPerformed

        private void showCandidatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCandidatesButtonActionPerformed
		if (systemManager.admin != null) {
			showCandidatesTextArea.setText(systemManager.cm.toString());
		} else {
			viewCandidatesErrorLabel.setText("You do not have permission to view candidate information");
		}
        }//GEN-LAST:event_showCandidatesButtonActionPerformed

        private void showVotersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showVotersButtonActionPerformed
		if (systemManager.admin != null) {
			try {
				showVotersTextArea.setText(systemManager.vm.getAllVoters());
			} catch (SQLException ex) {
				voterErrorLabel.setText("Could not access database");
				System.out.println("UI: Could not access database");
				Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			viewVotersErrorLabel.setText("You do not have permission to view voter information");
		}

        }//GEN-LAST:event_showVotersButtonActionPerformed

        private void tabbedPaneMenuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneMenuStateChanged
		// TODO add your handling code here:
		switch (tabbedPaneMenu.getSelectedIndex()) {
			case 0 ->
				showCandidatesTextArea.setText("");
			case 1 ->
				showVotersTextArea.setText("");
			case 2 -> {
				candidateFirstNameField.setText("");
				candidateSurnameField.setText("");
				candidateIDField.setText("");
				candidateClassComboBox.setSelectedIndex(0);
				candidateGradeComboBox.setSelectedIndex(0);
			}
			case 3 -> {
				voterIDTextField.setText("");
				voterUsernameTextField.setText("");
				voterPasswordTextField.setText("");
				voterConfirmPasswordTextField.setText("");
				voterFirstNameTextField.setText("");
				voterSurnameTextField.setText("");
				voterGradeComboBox.setSelectedIndex(0);
				voterClassComboBox.setSelectedIndex(0);
			}
		}
        }//GEN-LAST:event_tabbedPaneMenuStateChanged

        private void addVoterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoterButtonActionPerformed
		if (systemManager.admin != null) {
			String vID = voterIDTextField.getText();
			String vUsername = voterUsernameTextField.getText();
			String vPassword = voterPasswordTextField.getText();
			String vFirstName = voterFirstNameTextField.getText();
			String vLastName = voterSurnameTextField.getText();
			String vClass = voterGradeComboBox.getSelectedItem() + "" + voterClassComboBox.getSelectedItem();

			try {
				systemManager.vm.addNewVoter(new Voter(vID, vFirstName, vLastName, vPassword, vUsername, vClass));
				voterErrorLabel.setText("Voter successfully added");
			} catch (SQLException ex) {
				Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
				voterErrorLabel.setText("Could not connect to database");
			}
		} else {
			voterErrorLabel.setText("You do not have permission to add voters");
		}

        }//GEN-LAST:event_addVoterButtonActionPerformed

        private void voteForCandidateStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteForCandidateStartButtonActionPerformed
		// TODO add your handling code here:
		systemManager.cm.setCurrentCandidate(0);
		Candidate c = systemManager.cm.getCurrentCandidate();
		updateVoteForCandidatesPanel(c);
        }//GEN-LAST:event_voteForCandidateStartButtonActionPerformed

        private void voteForCandidatePreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteForCandidatePreviousButtonActionPerformed
		// TODO add your handling code here:
		Candidate c = systemManager.cm.previousCandidate();
		updateVoteForCandidatesPanel(c);
        }//GEN-LAST:event_voteForCandidatePreviousButtonActionPerformed

        private void voteForCandidateNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteForCandidateNextButtonActionPerformed
		// TODO add your handling code here:
		Candidate c = systemManager.cm.nextCandidate();
		updateVoteForCandidatesPanel(c);
        }//GEN-LAST:event_voteForCandidateNextButtonActionPerformed

        private void voteForCandidateEndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteForCandidateEndButtonActionPerformed
		// TODO add your handling code here:
		systemManager.cm.setCurrentCandidate(systemManager.cm.getSize() - 1);
		Candidate c = systemManager.cm.getCurrentCandidate();
		updateVoteForCandidatesPanel(c);
        }//GEN-LAST:event_voteForCandidateEndButtonActionPerformed

        private void voteForCandidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteForCandidateButtonActionPerformed
		if (systemManager.voter != null) {
			try {
				systemManager.vm.vote(systemManager.cm.getCurrentCandidate());
				JOptionPane.showMessageDialog(null, "Vote successful!", "Vote slip", JOptionPane.DEFAULT_OPTION);
			} catch (SQLException ex) {
				System.out.println("MM: Could not connect to database");
				voteForCandidateErrorLabel.setText("Could not connect to database");
				Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			voteForCandidateErrorLabel.setText("You are not a registered voter. Login as voter to vote.");
		}
        }//GEN-LAST:event_voteForCandidateButtonActionPerformed

        private void calculateVotesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateVotesButtonActionPerformed
		if (systemManager.admin != null) {
			try {
				calculateVotesTextArea.setText(systemManager.vm.voteCount());
			} catch (SQLException ex) {
				System.out.println("MM: could not connect to database");
				calculateVotesErrorLabel.setText("Could not connect to database");
				Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			calculateVotesErrorLabel.setText("You do not have permission to view voting information");
		}
        }//GEN-LAST:event_calculateVotesButtonActionPerformed

	private void updateVoteForCandidatesPanel(Candidate c) {
		votingCandidateFirstName.setText(c.getName());
		votingCandidateSurname.setText(c.getSurname());
		ImageIcon icon = new ImageIcon(new ImageIcon(getClass().getResource("/images/" + c.getName() + ".jpg")).getImage().getScaledInstance(163, 171, Image.SCALE_DEFAULT));
		voteForCandidateImageLabel.setIcon(icon);
	}

	private static void initLookAndFeel() {
		String lookAndFeel = null;

		if (LOOKANDFEEL != null) {
			if (LOOKANDFEEL.equals("Metal")) {
				lookAndFeel = UIManager.getCrossPlatformLookAndFeelClassName();
				//  an alternative way to set the Metal L&F is to replace the
				// previous line with:
				// lookAndFeel = "javax.swing.plaf.metal.MetalLookAndFeel";

			} else if (LOOKANDFEEL.equals("System")) {
				lookAndFeel = UIManager.getSystemLookAndFeelClassName();
			} else if (LOOKANDFEEL.equals("Motif")) {
				lookAndFeel = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
			} else if (LOOKANDFEEL.equals("GTK")) {
				lookAndFeel = "com.sun.java.swing.plaf.gtk.GTKLookAndFeel";
			} else {
				System.err.println("Unexpected value of LOOKANDFEEL specified: "
					+ LOOKANDFEEL);
				lookAndFeel = UIManager.getCrossPlatformLookAndFeelClassName();
			}

			try {

//				UIManager.setLookAndFeel(lookAndFeel);
				UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());

				// If L&F = "Metal", set the theme
				if (LOOKANDFEEL.equals("Metal")) {
					if (THEME.equals("DefaultMetal")) {
						MetalLookAndFeel.setCurrentTheme(new DefaultMetalTheme());
					} else if (THEME.equals("Ocean")) {
						MetalLookAndFeel.setCurrentTheme(new OceanTheme());
					}

					UIManager.setLookAndFeel(new MetalLookAndFeel());
				}

//			} catch (ClassNotFoundException e) {
//				System.err.println("Couldn't find class for specified look and feel:"
//					+ lookAndFeel);
//				System.err.println("Did you include the L&F library in the class path?");
//				System.err.println("Using the default look and feel.");
			} catch (UnsupportedLookAndFeelException e) {
				System.err.println("Can't use the specified look and feel ("
					+ lookAndFeel
					+ ") on this platform.");
				System.err.println("Using the default look and feel.");
			} catch (Exception e) {
				System.err.println("Couldn't get specified look and feel ("
					+ lookAndFeel
					+ "), for some reason.");
				System.err.println("Using the default look and feel.");
				e.printStackTrace();
			}

		}
		//Make sure we have nice window decorations.
		JFrame.setDefaultLookAndFeelDecorated(true);

	}

	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//		 */
////		try {
////			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
//////			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//////				System.out.println(info.getName());
//////				if ("Nimbus".equals(info.getName())) {
//////					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//////					break;
//////				}
//////			}
////		} catch (ClassNotFoundException ex) {
////			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////		} catch (InstantiationException ex) {
////			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////		} catch (IllegalAccessException ex) {
////			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
////			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////		}
//		//</editor-fold>
//
//		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new MainMenu().setVisible(true);
//			}
//		});
//	}
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addCandidateHelpButton;
        private javax.swing.JPanel addCandidatePanel;
        private javax.swing.JButton addVoterButton;
        private javax.swing.JButton addVoterHelpButton;
        private javax.swing.JPanel addVoterPanel;
        private javax.swing.JButton calculateVotesButton;
        private javax.swing.JLabel calculateVotesErrorLabel;
        private javax.swing.JButton calculateVotesHelpButton;
        private javax.swing.JPanel calculateVotesPanel;
        private javax.swing.JTextArea calculateVotesTextArea;
        private javax.swing.JButton candidateAddButton;
        private javax.swing.JComboBox<String> candidateClassComboBox;
        private javax.swing.JTextField candidateFirstNameField;
        private javax.swing.JComboBox<String> candidateGradeComboBox;
        private javax.swing.JTextField candidateIDField;
        private javax.swing.JTextField candidateSurnameField;
        private javax.swing.JLabel candidatesErrorLabel;
        private javax.swing.JTextField endDateTextField;
        private javax.swing.JLabel helpErrorLabel;
        private javax.swing.JButton jButton12;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JButton setDatesButton;
        private javax.swing.JLabel setDatesErrorLabel;
        private javax.swing.JButton setDatesHelpButton;
        private javax.swing.JPanel setDatesPanel;
        private javax.swing.JButton showCandidatesButton;
        private javax.swing.JTextArea showCandidatesTextArea;
        private javax.swing.JButton showVotersButton;
        private javax.swing.JTextArea showVotersTextArea;
        private javax.swing.JTextField startDateTextField;
        private javax.swing.JTabbedPane tabbedPaneMenu;
        private javax.swing.JButton viewCandidateHelpButton;
        private javax.swing.JPanel viewCandidatePanel;
        private javax.swing.JLabel viewCandidatesErrorLabel;
        private javax.swing.JLabel viewVotersErrorLabel;
        private javax.swing.JButton viewVotersHelpButton;
        private javax.swing.JPanel viewVotersPanel;
        private javax.swing.JButton voteForCandidateButton;
        private javax.swing.JButton voteForCandidateEndButton;
        private javax.swing.JLabel voteForCandidateErrorLabel;
        private javax.swing.JButton voteForCandidateHelpButton;
        private javax.swing.JLabel voteForCandidateImageLabel;
        private javax.swing.JButton voteForCandidateNextButton;
        private javax.swing.JPanel voteForCandidatePanel;
        private javax.swing.JButton voteForCandidatePreviousButton;
        private javax.swing.JButton voteForCandidateStartButton;
        private javax.swing.JComboBox<String> voterClassComboBox;
        private javax.swing.JTextField voterConfirmPasswordTextField;
        private javax.swing.JLabel voterErrorLabel;
        private javax.swing.JTextField voterFirstNameTextField;
        private javax.swing.JComboBox<String> voterGradeComboBox;
        private javax.swing.JTextField voterIDTextField;
        private javax.swing.JTextField voterPasswordTextField;
        private javax.swing.JTextField voterSurnameTextField;
        private javax.swing.JTextField voterUsernameTextField;
        private javax.swing.JTextField votingCandidateFirstName;
        private javax.swing.JTextField votingCandidateSurname;
        // End of variables declaration//GEN-END:variables
}
